// This class generated by CodeSmith on 2024年8月22日


<template>
  <UnitTable />
</template>

<script lang="ts">
  import { defineComponent } from 'vue';

  import UnitTable from './components/UnitTable.vue';
  export default defineComponent({
    name: 'Units',
    components: {
      UnitTable,
    },
    setup() {},
  });
</script>
