// This class generated by CodeSmith on 2024年8月19日


<template>
  <CategoryTable />
</template>

<script lang="ts">
  import { defineComponent } from 'vue';

  import CategoryTable from './components/CategoryTable.vue';
  export default defineComponent({
    name: 'Categorys',
    components: {
      CategoryTable,
    },
    setup() {},
  });
</script>
