<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Zion.Sales</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Zion.Sales.Domain\Zion.Sales.Domain.csproj" />
    <ProjectReference Include="..\Zion.Sales.TestBase\Zion.Sales.TestBase.csproj" />
  </ItemGroup>


</Project>
