// This class generated by CodeSmith on 2024年8月15日


<template>
  <CompanyTable />
</template>

<script lang="ts">
  import { defineComponent } from 'vue';

  import CompanyTable from './components/CompanyTable.vue';


  export default defineComponent({
    name: 'Companys',
    components: {
      CompanyTable,
    },
    setup() {},
  });
</script>
