// This class generated by CodeSmith on 2024年8月22日


import { number } from "vue-types";

export interface Unit{
  id: string;
  name: string;
}


export interface CreateOrUpdateUnitBase {
  name: string;
}

export interface CreateUnit extends CreateOrUpdateUnitBase {
    
}

export interface UpdateUnit extends CreateOrUpdateUnitBase {

}

export interface GetUnitPagedRequest extends PagedAndSortedResultRequestDto {
  name: string;
}

