// This class generated by CodeSmith on 2024年8月22日

//系统模块
import type { Ref } from 'vue';
import type { TabFormSchema, TabFormActionType } from '/@/components/Form/src/types/form';
import { unref, computed, watch, createVNode } from 'vue';
import { useLocalization } from '/@/hooks/abp/useLocalization';
import { cloneDeep } from 'lodash-es';
import { listToTree } from '/@/utils/helper/treeHelper';

//自有模块
import { getList, create, update } from '/@/api/product/product';
import { getList as brandGetList } from '/@/api/product/brand'
import { getTreeList as categoryGetTreeList } from '/@/api/product/category'
import { Product, UpdateProduct, CreateProduct } from '/@/api/product/product/model';

interface UseProductFormContext {
  productModel: Ref<Product>;
  formElRef: Ref<Nullable<TabFormActionType>>;
}

export function useProductFormContext({ productModel, formElRef }: UseProductFormContext) {
  console.log("module is");
  console.log(productModel);

  const { L } = useLocalization(['AppPlatform','System','Product']);

  function getBasicFormSchemas(): TabFormSchema[] {
    return [
      {
        tab: L('DisplayName:Basic'),
        field: 'id',
        component: 'Input',
        label: 'id',
        colProps: { span: 24 },
        ifShow: false,
        required:true
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'code',
        component: 'Input',
        label: L('DisplayName:Code'),
        colProps: { span: 24 },
        required: true,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'name',
        component: 'Input',
        label: L('DisplayName:Name'),
        colProps: { span: 24 },
        required: true,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'brandId',
        component: 'ApiSelect',
        componentProps: {
          showSearch: true, // 开启搜索
          api: ()=>brandGetList({}),
          resultField:'items',
          immediate:true,
          labelField: 'name',
          valueField: 'id',
          optionFilterProp:'name', // 搜索按name字段搜索
        },
        label: L('DisplayName:Brand'),
        colProps: { span: 24 },
        required: false,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'categoryId',
        component: 'ApiTreeSelect',
        label: L('DisplayName:Category'),
        colProps: { span: 24 },
        required: false,
        componentProps: {
          api: ()=>categoryGetTreeList(),
          treeNodeFilterProp: 'name',
          //resultField:'items',
          immediate:true,
          showSearch: true,
          fieldNames: {
            label: "name",
            key: "id",
            value: "id",
            children:"children"
          },
          onChange: (e, v) => {
            console.log('ApiTreeSelect====>:', e, v);
          },
        }
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'description',
        component: 'Input',
        label: L('DisplayName:Description'),
        colProps: { span: 24 },
        required: false,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'imageUrl',
        component: 'Input',
        label: L('DisplayName:ImageUrl'),
        colProps: { span: 24 },
        required: false,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'isSuggest',
        component: 'Checkbox',
        defaultValue: false,
        label: L('DisplayName:IsSuggest'),
        colProps: { span: 24 },
        required: true,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'isValid',
        component: 'Checkbox',
        defaultValue: true,
        label: L('DisplayName:IsValid'),
        colProps: { span: 24 },
        required: true,
      },
      
    ];
  }

  const getFormSchemas = computed((): TabFormSchema[] => {
    return [...getBasicFormSchemas()];
  });

  const formTitle = computed((): string => {
    const product = unref(productModel);
    if(!product) return "";
    if (product.id) {
      return L('Menu:EditByName', [product.name] as Recordable);
    }
    return L('Menu:AddNew');
  });

  /* 使用此填充下拉列表
  async function fetchProductResource() {
    removeAllParentMenus();
    const formEl = unref(formElRef);
    const { items } = await getList({});
    const treeData = listToTree(items, { id: 'code', pid: 'parentCode' });
    const region = unref(regionModel);
    formEl?.updateSchema({
      field: 'parentCode',
      defaultValue: region.parentCode,
      componentProps: { treeData },
    });
  }
  */

  function handleFormSubmit() {
    const formEl = unref(formElRef);
    return formEl?.validate().then(() => {
      const model = unref(productModel);
      const input = formEl?.getFieldsValue();
      return model.id
        ? update(model.id, cloneDeep(input) as UpdateProduct)
        : create(cloneDeep(input) as CreateProduct);
    });
  }

  watch(
    () => unref(productModel),
    (newModel) => {
      const formEl = unref(formElRef);
      formEl?.resetFields();
      formEl?.setFieldsValue(newModel);
    },
    { immediate: true },
  );

  return {
    formTitle,
    getFormSchemas,
    handleFormSubmit,
    //fetchProductResource,
  };
}


