// This class generated by CodeSmith on 2024年8月15日

//系统组件
import { BasicColumn } from '/@/components/Table/src/types/table';
import { useLocalization } from '/@/hooks/abp/useLocalization';
const { L } = useLocalization(['AppPlatform','System']);

// 自有组件


export function getDataColumns(): BasicColumn[] {
  return [
    {
      title: 'id',
      dataIndex: 'id',
      width: 1,
      ifShow: false,
    },
    {
      title: L('DisplayName:Name'),
      dataIndex: 'name',
      align: 'left',
      width: 150,
      resizable: true,
    },
    {
      title: L('DisplayName:ShortName'),
      dataIndex: 'shortName',
      align: 'left',
      width: 150,
      resizable: true,
    },
    
  ];
}
