// This class generated by CodeSmith on 2024年8月15日

//系统组件
import { useLocalization } from '/@/hooks/abp/useLocalization';
import { FormProps } from '/@/components/Form';
const { L } = useLocalization(['AppPlatform','System']);

// 自有组件


// 搜索用到的模型
export function getSearchFormSchemas(): Partial<FormProps> {
  return {
    labelWidth: 100,
    schemas: [
      {
        field: 'name',
        component: 'Input',
        label: L('DisplayName:Name'),
        colProps: { span: 8 },
      },
      {
        field: 'shortName',
        component: 'Input',
        label: L('DisplayName:ShortName'),
        colProps: { span: 8 },
      },
      /*
      {
        field: 'layoutId',
        component: 'ApiSelect',
        label: L('DisplayName:Layout'),
        colProps: { span: 8 },
        componentProps: {
          api: () => getAllLayout(),
          resultField: 'items',
          labelField: 'displayName',
          valueField: 'id',
        },
      },
      */
    ],
  };
}

