// This class generated by CodeSmith on 2024年8月15日


import { number } from "vue-types";

export interface Company{
  id: string;
  name: string;
  shortName:string;
}


export interface CreateOrUpdateCompanyBase {
  name: string;
  shortName:string;
}

export interface CreateCompany extends CreateOrUpdateCompanyBase {
    
}

export interface UpdateCompany extends CreateOrUpdateCompanyBase {

}

export interface GetCompanyPagedRequest extends PagedAndSortedResultRequestDto {
  name: string;
}

