// This class generated by CodeSmith on 2024年8月22日

//系统组件
import { useLocalization } from '/@/hooks/abp/useLocalization';
import { FormProps } from '/@/components/Form';
const { L } = useLocalization(['AppPlatform','System','Product']);

// 自有组件


// 搜索用到的模型
export function getSearchFormSchemas(): Partial<FormProps> {
  return {
    labelWidth: 100,
    schemas: [
      {
        field: 'code',
        component: 'Input',
        label: L('DisplayName:Code'),
        colProps: { span: 8 },
      },
      {
        field: 'name',
        component: 'Input',
        label: L('DisplayName:Name'),
        colProps: { span: 8 },
      },
      {
        field: 'brandId',
        component: 'Input',
        label: L('DisplayName:Brand'),
        colProps: { span: 8 },
      },
      {
        field: 'categoryId',
        component: 'Input',
        label: L('DisplayName:Category'),
        colProps: { span: 8 },
      },
      {
        field: 'isSuggest',
        component: 'Input',
        label: L('DisplayName:IsSuggest'),
        colProps: { span: 8 },
      },
      {
        field: 'description',
        component: 'Input',
        label: L('DisplayName:Description'),
        colProps: { span: 8 },
      },
      {
        field: 'isValid',
        component: 'Input',
        label: L('DisplayName:IsValid'),
        colProps: { span: 8 },
      },
      /*
      {
        field: 'layoutId',
        component: 'ApiSelect',
        label: L('DisplayName:Layout'),
        colProps: { span: 8 },
        componentProps: {
          api: () => getAllLayout(),
          resultField: 'items',
          labelField: 'displayName',
          valueField: 'id',
        },
      },
      */
    ],
  };
}

