// This class generated by CodeSmith on 2024年8月22日


<template>
  <div>
    <BasicTable @register="registerTable">
      <template #toolbar>
        <a-button v-auth="['Product.Product.Create']" type="primary" @click="handleAddNew">{{
          L('AddNew')
        }}</a-button>
      </template>
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'isValid'">
          <a-tag
            :color="record.isValid? 'green' : 'red'"
          >
            {{ record.isValid?'有效':'无效' }}
          </a-tag>
        </template>
        <template v-if="column.key === 'isSuggest'">
          <LikeOutlined v-if="record.isSuggest" style="color:green"/>
          <!-- <a-tag
            :color="record.isSuggest? 'green' : 'transparent'"
          >
            {{ record.isSuggest?'推荐':'' }}
          </a-tag> -->
        </template>
        <template v-if="column.key === 'brand'">
          
            {{ record.brand?record.brand.name:"" }}
          
        </template>
        <template v-if="column.key === 'category'">
          
          {{ record.category?record.category.name:"" }}
        
      </template>
        <template v-else-if="column.key === 'action'">
          <TableAction
            :actions="[
              {
                auth: 'Product.Product.Update',
                label: L('Edit'),
                icon: 'ant-design:edit-outlined',
                onClick: handleEdit.bind(null, record),
              },
              {
                auth: 'Product.Product.Delete',
                color: 'error',
                label: L('Delete'),
                icon: 'ant-design:delete-outlined',
                onClick: handleDelete.bind(null, record),
              },
            ]"
          />
        </template>
      </template>
    </BasicTable>
    <ProductDrawer @register="registerDrawer" @change="handleChange" :framework="useFramework" />
  </div>
</template>

<script lang="ts" setup>
  // 系统组件
  import { ref } from 'vue';
  import { useMessage } from '/@/hooks/web/useMessage';
  import { useLocalization } from '/@/hooks/abp/useLocalization';
  import { BasicTable, useTable, TableAction } from '/@/components/Table';
  import { useDrawer } from '/@/components/Drawer';
  import { LikeOutlined } from '@ant-design/icons-vue';
  //import { listToTree } from '/@/utils/helper/treeHelper';
  
  // 自有组件  
  import { getDataColumns } from './ProductData';
  import { getSearchFormSchemas } from './ModalData';
  import { getList, getById, deleteById } from '/@/api/product/product';
  import ProductDrawer from './ProductDrawer.vue';

  const { createMessage, createConfirm } = useMessage();
  const { L } = useLocalization(['AppPlatform', 'AbpUi', 'System','Product']);

  const useFramework = ref('');
  const [registerTable, { reload }] = useTable({
    rowKey: 'code',
    title: L('DisplayName:Product'),
    columns: getDataColumns(),
    api: getList,
    beforeFetch: (request) => {
      // 子组件需要此参数,拦截一下
      useFramework.value = request.framework;
      return request;
    },
    /*
    afterFetch: (result) => {
      return listToTree(result, {
        id: 'code',
        pid: 'parentCode',
      });
    },
    */
    pagination: false,
    striped: false,
    useSearchForm: true,
    showTableSetting: true,
    bordered: true,
    showIndexColumn: false,
    canResize: false,
    formConfig: getSearchFormSchemas(),
    actionColumn: {
      width: 280,
      title: L('Actions'),
      dataIndex: 'action',
    },
  });

  const [registerDrawer, { openDrawer }] = useDrawer();

  function handleAddNew(record?: Recordable) {
    openDrawer(true, {});
  }

  function handleEdit(record: Recordable) {
    getById(record.id).then((data) => {
      openDrawer(true, data);
    });
  }

  function handleDelete(record: Recordable) {
    createConfirm({
      iconType: 'warning',
      title: L('AreYouSure'),
      content: L('ItemWillBeDeletedMessageWithFormat', [record.name]),
      okCancel: true,
      onOk: () => {
        return deleteById(record.id).then(() => {
          createMessage.success(L('SuccessfullyDeleted'));
          reload();
        });
      },
    });
  }

  function handleChange() {
    console.log("on handle change called");
    reload();
  }
</script>

