// This class generated by CodeSmith on 2024年8月22日

//系统组件
import { BasicColumn } from '/@/components/Table/src/types/table';
import { useLocalization } from '/@/hooks/abp/useLocalization';
const { L } = useLocalization(['AppPlatform','System','Product']);

// 自有组件


export function getDataColumns(): BasicColumn[] {
  return [
    {
      title: 'id',
      dataIndex: 'id',
      width: 1,
      ifShow: false,
    },

    {
      title: L('DisplayName:Code'),
      dataIndex: 'code',
      align: 'left',
      width: 150,
      resizable: true,
    },
    {
      title: L('DisplayName:Name'),
      dataIndex: 'name',
      align: 'left',
      width: 150,
      resizable: true,
    },
    // {
    //   title: L('DisplayName:Brand'),
    //   dataIndex: 'brandId',
    //   align: 'left',
    //   width: 150,
    //   resizable: true,
    // },
    {
      title: L('DisplayName:Brand'),
      dataIndex: 'brand',
      align: 'left',
      width: 150,
      resizable: true,
    },
    // {
    //   title: L('DisplayName:Brand'),
    //   dataIndex: ['brand','name'],
    //   align: 'left',
    //   width: 150,
    //   resizable: true,
    // },
    // {
    //   title: L('DisplayName:Category'),
    //   dataIndex:  'categoryId',
    //   align: 'left',
    //   width: 150,
    //   resizable: true,
    // },

    {
      title: L('DisplayName:Category'),
      dataIndex: 'category',
      align: 'left',
      width: 150,
      resizable: true,
    },
    {
      title: L('DisplayName:IsSuggest'),
      dataIndex: 'isSuggest',
      align: 'left',
      width: 150,
      resizable: true,
    },
    {
      title: L('DisplayName:Description'),
      dataIndex: 'description',
      align: 'left',
      width: 150,
      resizable: true,
    },
    {
      title: L('DisplayName:IsValid'),
      dataIndex: 'isValid',
      align: 'left',
      width: 150,
      resizable: true
    },
  ];
}
