// This class generated by CodeSmith on 2024年8月22日

//系统模块
import type { Ref } from 'vue';
import type { TabFormSchema, TabFormActionType } from '/@/components/Form/src/types/form';
import { unref, computed, watch, createVNode } from 'vue';
import { useLocalization } from '/@/hooks/abp/useLocalization';
import { cloneDeep } from 'lodash-es';
import { listToTree } from '/@/utils/helper/treeHelper';

//自有模块
import { getList, create, update } from '/@/api/product/brand';
import { Brand, UpdateBrand, CreateBrand } from '/@/api/product/brand/model';

interface UseBrandFormContext {
  brandModel: Ref<Brand>;
  formElRef: Ref<Nullable<TabFormActionType>>;
}

export function useBrandFormContext({ brandModel, formElRef }: UseBrandFormContext) {
  console.log("module is");
  console.log(brandModel);

  const { L } = useLocalization(['AppPlatform','System','Product']);

  function getBasicFormSchemas(): TabFormSchema[] {
    return [
      {
        tab: L('DisplayName:Basic'),
        field: 'id',
        component: 'Input',
        label: 'id',
        colProps: { span: 24 },
        ifShow: false,
        required:true
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'name',
        component: 'Input',
        label: L('DisplayName:Name'),
        colProps: { span: 24 },
        required: true,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'jp',
        component: 'Input',
        label: L('DisplayName:JP'),
        colProps: { span: 24 },
        required: true,
        ifShow: ({ values }) => {
          return values.id ? true : false;
        },
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'initialChar',
        component: 'Input',
        label: L('DisplayName:InitialChar'),
        colProps: { span: 24 },
        required: true,
        ifShow: ({ values }) => {
          return values.id ? true : false;
        },
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'imageUrl',
        component: 'Input',
        label: L('DisplayName:ImageUrl'),
        colProps: { span: 24 },
        required: false,
      },
    ];
  }

  const getFormSchemas = computed((): TabFormSchema[] => {
    return [...getBasicFormSchemas()];
  });

  const formTitle = computed((): string => {
    const brand = unref(brandModel);
    if(!brand) return "";
    if (brand.id) {
      return L('Menu:EditByName', [brand.name] as Recordable);
    }
    return L('Menu:AddNew');
  });

  /* 使用此填充下拉列表
  async function fetchBrandResource() {
    removeAllParentMenus();
    const formEl = unref(formElRef);
    const { items } = await getList({});
    const treeData = listToTree(items, { id: 'code', pid: 'parentCode' });
    const region = unref(regionModel);
    formEl?.updateSchema({
      field: 'parentCode',
      defaultValue: region.parentCode,
      componentProps: { treeData },
    });
  }
  */

  function handleFormSubmit() {
    const formEl = unref(formElRef);
    return formEl?.validate().then(() => {
  
      const model = unref(brandModel);
      const input = formEl?.getFieldsValue();
      return model.id
        ? update(model.id, cloneDeep(input) as UpdateBrand)
        : create(cloneDeep(input) as CreateBrand);
    });
  }

  watch(
    () => unref(brandModel),
    (newModel) => {
      const formEl = unref(formElRef);
      formEl?.resetFields();
      formEl?.setFieldsValue(newModel);
    },
    { immediate: true },
  );

  return {
    formTitle,
    getFormSchemas,
    handleFormSubmit,
    //fetchBrandResource,
  };
}


