<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Zion.Sales</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore"  />
    <ProjectReference Include="..\Zion.Sales.Domain\Zion.Sales.Domain.csproj" />
  </ItemGroup>

</Project>
