// This class generated by CodeSmith on 2024年8月22日


<template>
  <ProductTable />
</template>

<script lang="ts">
  import { defineComponent } from 'vue';

  import ProductTable from './components/ProductTable.vue';
  export default defineComponent({
    name: 'Products',
    components: {
      ProductTable,
    },
    setup() {},
  });
</script>
