// This class generated by CodeSmith on 2024年8月23日

//系统组件
import { BasicColumn } from '/@/components/Table/src/types/table';
import { useLocalization } from '/@/hooks/abp/useLocalization';
const { L } = useLocalization(['AppPlatform','System','System']);

// 自有组件


export function getDataColumns(): BasicColumn[] {
  return [
    {
      title: 'id',
      dataIndex: 'id',
      width: 1,
      ifShow: false,
    },
    {
      title: L('DisplayName:Name'),
      dataIndex: 'name',
      align: 'left',
      width: 150,
      resizable: true,
    },
    {
      title: L('DisplayName:SortOrder'),
      dataIndex: 'sortOrder',
      align: 'left',
      width: 150,
      resizable: true,
    },
    {
      title: L('DisplayName:TypeCode'),
      dataIndex: 'typeCode',
      align: 'left',
      width: 150,
      resizable: true,
    },
    {
      title: L('DisplayName:ExpDateTime'),
      dataIndex: 'expDateTime',
      align: 'left',
      width: 150,
      resizable: true,
    },
    {
      title: L('DisplayName:Description'),
      dataIndex: 'description',
      align: 'left',
      width: 150,
      resizable: true,
    },
  ];
}
