// This class generated by CodeSmith on 2024年8月23日


<template>
  <BasicDrawer
    v-bind="$attrs"
    @register="registerDrawer"
    showFooter
    :title="formTitle"
    width="50%"
    @ok="handleSubmit"
  >
    <TabForm
      ref="formElRef"
      :schemas="getFormSchemas"
      :label-width="120"
      :show-action-button-group="false"
      :base-col-props="{
        span: 24,
      }"
      :action-col-options="{
        span: 24,
      }"
    />
  </BasicDrawer>
</template>

<script lang="ts" setup>
  //系统模块
  import { nextTick, ref, unref } from 'vue';
  import { useMessage } from '/@/hooks/web/useMessage';
  import { useLocalization } from '/@/hooks/abp/useLocalization';
  import { TabForm, TabFormActionType } from '/@/components/Form';
  import { BasicDrawer, useDrawerInner } from '/@/components/Drawer';
  
  //自有模块
  import { basicProps } from './props';
  import { Ad } from '/@/api/system/ad/model';
  import { useAdFormContext } from '../hooks/useAdFormContext';
  

  const emits = defineEmits(['change', 'register']);
  const props = defineProps(basicProps); //抽屉的属性

  const { createMessage } = useMessage();
  const { L } = useLocalization(['AppPlatform', 'AbpUi']);
  const entity = ref<Ad>({} as Ad);
  const framework = ref<string | undefined>('');
  const formElRef = ref<Nullable<TabFormActionType>>(null);

  const { formTitle, getFormSchemas, handleFormSubmit /*,fetchAdResource*/ } = useAdFormContext({
    adModel: entity,
    formElRef: formElRef,
  });
  
  const [registerDrawer, { setDrawerProps, changeOkLoading, closeDrawer }] = useDrawerInner(
    //回调函数
    (dataVal) => {
      entity.value = dataVal;
      framework.value = props.framework;
      nextTick(() => {
        setDrawerProps({ confirmLoading: false });
        
        //fetchAdResource();

        const formEl = unref(formElRef);
        formEl?.changeTab(L('DisplayName:Basic'));
      });
    },
  );

  function handleSubmit() {
    changeOkLoading(true);
    handleFormSubmit()
      ?.then(() => {
        createMessage.success(L('Successful'));
        closeDrawer();
        emits('change');
      })
      .finally(() => {
        changeOkLoading(false);
      });
  }
</script>


