// This class generated by CodeSmith on 2024年8月23日


<template>
  <div>
    <BasicTable @register="registerTable">
      <template #toolbar>
        <a-button v-auth="['System.Ad.Create']" type="primary" @click="handleAddNew">{{
          L('AddNew')
        }}</a-button>
      </template>
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'name'">
          <span>{{ record.name}}</span>
        </template>
        <template v-else-if="column.key === 'action'">
          <TableAction
            :actions="[
              //{
              //  auth: 'System.Ad.Create',
              //  label: L('AddNew'),
              //  icon: 'ant-design:plus-outlined',
              //  onClick: handleAddNew.bind(null, record),
              //},
              {
                auth: 'System.Ad.Update',
                label: L('Edit'),
                icon: 'ant-design:edit-outlined',
                onClick: handleEdit.bind(null, record),
              },
              {
                auth: 'System.Ad.Delete',
                color: 'error',
                label: L('Delete'),
                icon: 'ant-design:delete-outlined',
                onClick: handleDelete.bind(null, record),
              },
            ]"
          />
        </template>
      </template>
    </BasicTable>
    <AdDrawer @register="registerDrawer" @change="handleChange" :framework="useFramework" />
  </div>
</template>

<script lang="ts" setup>
  // 系统组件
  import { ref } from 'vue';
  import { useMessage } from '/@/hooks/web/useMessage';
  import { useLocalization } from '/@/hooks/abp/useLocalization';
  import { BasicTable, useTable, TableAction } from '/@/components/Table';
  import { useDrawer } from '/@/components/Drawer';
  //import { listToTree } from '/@/utils/helper/treeHelper';
  
  // 自有组件  
  import { getDataColumns } from './AdData';
  import { getSearchFormSchemas } from './ModalData';
  import { getList, getById, deleteById } from '/@/api/system/ad';
  import AdDrawer from './AdDrawer.vue';

  const { createMessage, createConfirm } = useMessage();
  const { L } = useLocalization(['AppPlatform', 'AbpUi', 'System','System']);

  const useFramework = ref('');
  const [registerTable, { reload }] = useTable({
    rowKey: 'code',
    title: L('DisplayName:Ad'),
    columns: getDataColumns(),
    api: getList,
    beforeFetch: (request) => {
      // 子组件需要此参数,拦截一下
      useFramework.value = request.framework;
      return request;
    },
    /*
    afterFetch: (result) => {
      return listToTree(result, {
        id: 'code',
        pid: 'parentCode',
      });
    },
    */
    pagination: false,
    striped: false,
    useSearchForm: true,
    showTableSetting: true,
    bordered: true,
    showIndexColumn: false,
    canResize: false,
    formConfig: getSearchFormSchemas(),
    actionColumn: {
      width: 280,
      title: L('Actions'),
      dataIndex: 'action',
    },
  });

  const [registerDrawer, { openDrawer }] = useDrawer();

  function handleAddNew(record?: Recordable) {
    openDrawer(true, {});
  }

  function handleEdit(record: Recordable) {
    getById(record.id).then((data) => {
      openDrawer(true, data);
    });
  }

  function handleDelete(record: Recordable) {
    createConfirm({
      iconType: 'warning',
      title: L('AreYouSure'),
      content: L('ItemWillBeDeletedMessageWithFormat', [record.name]),
      okCancel: true,
      onOk: () => {
        return deleteById(record.id).then(() => {
          createMessage.success(L('SuccessfullyDeleted'));
          reload();
        });
      },
    });
  }

  function handleChange() {
    console.log("on handle change called");
    reload();
  }
</script>

