// This class generated by CodeSmith on 2024年8月23日

//系统组件
import { useLocalization } from '/@/hooks/abp/useLocalization';
import { FormProps } from '/@/components/Form';
const { L } = useLocalization(['AppPlatform','System','System']);

// 自有组件
import { getByName } from '/@/api/platform/datas';

// 搜索用到的模型
export function getSearchFormSchemas(): Partial<FormProps> {
  return {
    labelWidth: 100,
    schemas: [
      {
        field: 'name',
        component: 'Input',
        label: L('DisplayName:Name'),
        colProps: { span: 8 },
      },
      {
        field: 'typeCode',
        component: 'ApiSelect',
        label: L('DisplayName:AdTypeCode'),
        colProps: { span: 8 },
        componentProps: {
          showSearch: true, // 开启搜索
          api: ()=>getByName('AdType'),
          resultField:'items',
          immediate:true,
          labelField: 'displayName',
          valueField: 'defaultValue',
          optionFilterProp:'name', // 搜索按name字段搜索
        }
      },
      /*
      {
        field: 'layoutId',
        component: 'ApiSelect',
        label: L('DisplayName:Layout'),
        colProps: { span: 8 },
        componentProps: {
          api: () => getAllLayout(),
          resultField: 'items',
          labelField: 'displayName',
          valueField: 'id',
        },
      },
      */
    ],
  };
}

