// This class generated by CodeSmith on 2024年8月23日


<template>
  <AdTable />
</template>

<script lang="ts">
  import { defineComponent } from 'vue';

  import AdTable from './components/AdTable.vue';
  export default defineComponent({
    name: 'Ads',
    components: {
      AdTable,
    },
    setup() {},
  });
</script>
