// This class generated by CodeSmith on 2024年8月22日


import { number } from "vue-types";

export interface Brand{
  id: string;
  name: string;
}


export interface CreateOrUpdateBrandBase {
  name: string;
}

export interface CreateBrand extends CreateOrUpdateBrandBase {
    
}

export interface UpdateBrand extends CreateOrUpdateBrandBase {

}

export interface GetBrandPagedRequest extends PagedAndSortedResultRequestDto {
  name?: string;
}

