// This class generated by CodeSmith on 2024年8月19日

//系统模块
import type { Ref } from 'vue';
import type { TabFormSchema, TabFormActionType } from '/@/components/Form/src/types/form';
import { unref, computed, watch, createVNode } from 'vue';
import { useLocalization } from '/@/hooks/abp/useLocalization';
import { cloneDeep } from 'lodash-es';
import { listToTree } from '/@/utils/helper/treeHelper';

//自有模块
import { getList, create, update } from '/@/api/product/category';
import { Category, UpdateCategory, CreateCategory } from '/@/api/product/category/model';

interface UseCategoryFormContext {
  categoryModel: Ref<Category>;
  formElRef: Ref<Nullable<TabFormActionType>>;
}

export function useCategoryFormContext({ categoryModel, formElRef }: UseCategoryFormContext) {
  console.log("module is");
  console.log(categoryModel);

  const { L } = useLocalization(['AppPlatform','System','Product']);

  function getBasicFormSchemas(): TabFormSchema[] {
    return [
      {
        tab: L('DisplayName:Basic'),
        field: 'id',
        component: 'Input',
        label: 'id',
        colProps: { span: 24 },
        ifShow: false,
        required:true
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'name',
        component: 'Input',
        label: L('DisplayName:Name'),
        colProps: { span: 24 },
        required: true,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'imageUrl',
        component: 'Input',
        label: L('DisplayName:ImageUrl'),
        colProps: { span: 24 },
        required: true,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'parentId',
        component: 'TreeSelect',
        label: L('DisplayName:ParentCategory'),
        colProps: { span: 24 },
        required: false,
        componentProps: {
          fieldNames: {
            label: 'name',
            key: 'id',
            value: 'id',
          },
          getPopupContainer: () => document.body,
        },
      },
      {
        tab: L('DisplayName:SpecInfo'),
        field: 'SpecTemplateJsonData',
        component: 'InputTextArea',
        componentProps: {
          style:'height:500px'
        },
        label: L('DisplayName:Spec'),
        colProps: { span: 24 },
        required: true,
      }
    ];
  }

  const getFormSchemas = computed((): TabFormSchema[] => {
    return [...getBasicFormSchemas()];
  });

  const formTitle = computed((): string => {
    const category = unref(categoryModel);
    if(!category) return "";
    if (category.id) {
      return L('Menu:EditByName', [category.name] as Recordable);
    }
    return L('Menu:AddNew');
  });


  async function fetchCategoryResource() {
    removeAllParentMenus();
    const formEl = unref(formElRef);
    const { items } = await getList({});
    const treeData = listToTree(items, { id: 'id', pid: 'parentId' });
    //const category = unref(categoryModel);
    
    //更新options
    formEl?.updateSchema({
      field: 'parentId',
      //defaultValue: category.parentId,
      defaultValue: null,
      componentProps: { treeData },
    });
  }

  function removeAllParentMenus() {
    console.log('clear all node')
    const formEl = unref(formElRef);
    formEl?.updateSchema({
      field: 'parentId',
      componentProps: { treeData: [] },
    });
  }
  

  function handleFormSubmit() {
    const formEl = unref(formElRef);
    return formEl?.validate().then(() => {
      const model = unref(categoryModel);
      const input = formEl?.getFieldsValue();
      return model.id
        ? update(model.id, cloneDeep(input) as UpdateCategory)
        : create(cloneDeep(input) as CreateCategory);
    });
  }

  watch(
    () => unref(categoryModel),
    (newModel) => {
      const formEl = unref(formElRef);
      formEl?.resetFields();
      formEl?.setFieldsValue(newModel);
    },
    { immediate: true },
  );

  return {
    formTitle,
    getFormSchemas,
    handleFormSubmit,
    fetchCategoryResource,
  };
}


