// This class generated by CodeSmith on 2024年8月19日


import { number } from "vue-types";

export interface Category{
  id: string;
  name: string;
  parentId?:string;
}


export interface CreateOrUpdateCategoryBase {
  name: string;
}

export interface CreateCategory extends CreateOrUpdateCategoryBase {
  parentId?:string;
}

export interface UpdateCategory extends CreateOrUpdateCategoryBase {

}

export interface GetCategoryPagedRequest extends PagedAndSortedResultRequestDto {
  name?: string;
}

export interface CategoryTreeItem{
  id:string;
  name:string;
  parentId:string;
  children:CategoryTreeItem[]
}

