// This class generated by CodeSmith on 2024年8月22日


import { number } from "vue-types";

export interface Product{
  id: string;
  name: string;
}


export interface CreateOrUpdateProductBase {
  name: string;
}

export interface CreateProduct extends CreateOrUpdateProductBase {
    
}

export interface UpdateProduct extends CreateOrUpdateProductBase {

}

export interface GetProductPagedRequest extends PagedAndSortedResultRequestDto {
  name: string;
}

