// This class generated by CodeSmith on 2024年8月23日

//系统模块
import type { Ref } from 'vue';
import type { TabFormSchema, TabFormActionType } from '/@/components/Form/src/types/form';
import { unref, computed, watch, createVNode } from 'vue';
import { useLocalization } from '/@/hooks/abp/useLocalization';
import { cloneDeep } from 'lodash-es';
import { listToTree } from '/@/utils/helper/treeHelper';
import dayjs from 'dayjs';
//自有模块
import { getList, create, update } from '/@/api/system/ad';
import { getByName } from '/@/api/platform/datas';
import { Ad, UpdateAd, CreateAd } from '/@/api/system/ad/model';

interface UseAdFormContext {
  adModel: Ref<Ad>;
  formElRef: Ref<Nullable<TabFormActionType>>;
}

export function useAdFormContext({ adModel, formElRef }: UseAdFormContext) {
  console.log("module is");
  console.log(adModel);

  const { L } = useLocalization(['AppPlatform','System','System']);

  function getBasicFormSchemas(): TabFormSchema[] {
    return [
      {
        tab: L('DisplayName:Basic'),
        field: 'id',
        component: 'Input',
        label: 'id',
        colProps: { span: 24 },
        ifShow: false,
        required:true
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'name',
        component: 'Input',
        label: L('DisplayName:Name'),
        colProps: { span: 24 },
        required: true,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'imageUrl',
        component: 'Input',
        label: L('DisplayName:ImageUrl'),
        colProps: { span: 24 },
        required: true,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'sortOrder',
        component: 'Input',
        defaultValue:'',
        componentProps: ({ formModel }) => {
          return {
            oninput: (e) => {
              formModel.sortOrder = formModel.sortOrder.replace(/\D*/g, '');
            },
          };
        },
        label: L('DisplayName:SortOrder'),
        colProps: { span: 24 },
        required: true,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'typeCode',
        component: 'ApiSelect',
        componentProps: {
          showSearch: true, // 开启搜索
          api: ()=>getByName('AdType'),
          resultField:'items',
          immediate:true,
          labelField: 'displayName',
          valueField: 'defaultValue',
          optionFilterProp:'name', // 搜索按name字段搜索
        },
        label: L('DisplayName:AdTypeCode'),
        colProps: { span: 24 },
        required: true,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'targetUrl',
        component: 'Input',
        label: L('DisplayName:TargetUrl'),
        colProps: { span: 24 },
        required: true,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'expDateTime',
        component: 'DatePicker',
        componentProps:{
          showTime:{
            defaultValue: dayjs('23:59:59', 'HH:mm:ss') 
          }
        },
        label: L('DisplayName:ExpDateTime'),
        colProps: { span: 24 },
        required: true,
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'description',
        component: 'Input',
        label: L('DisplayName:Description'),
        colProps: { span: 24 },
        required: true,
      },
    ];
  }

  const getFormSchemas = computed((): TabFormSchema[] => {
    return [...getBasicFormSchemas()];
  });

  const formTitle = computed((): string => {
    const ad = unref(adModel);
    if(!ad) return "";
    if (ad.id) {
      return L('Menu:EditByName', [ad.name] as Recordable);
    }
    return L('Menu:AddNew');
  });

  /* 使用此填充下拉列表
  async function fetchAdResource() {
    removeAllParentMenus();
    const formEl = unref(formElRef);
    const { items } = await getList({});
    const treeData = listToTree(items, { id: 'code', pid: 'parentCode' });
    const region = unref(regionModel);
    formEl?.updateSchema({
      field: 'parentCode',
      defaultValue: region.parentCode,
      componentProps: { treeData },
    });
  }
  */

  function handleFormSubmit() {
    const formEl = unref(formElRef);
    return formEl?.validate().then(() => {
      const model = unref(adModel);
      const input = formEl?.getFieldsValue();
      return model.id
        ? update(model.id, cloneDeep(input) as UpdateAd)
        : create(cloneDeep(input) as CreateAd);
    });
  }

  watch(
    () => unref(adModel),
    (newModel) => {
      const formEl = unref(formElRef);
      formEl?.resetFields();
      formEl?.setFieldsValue(newModel);
    },
    { immediate: true },
  );

  return {
    formTitle,
    getFormSchemas,
    handleFormSubmit,
    //fetchAdResource,
  };
}


