// This class generated by CodeSmith on 2024年8月15日

//系统模块
import type { Ref } from 'vue';
import type { TabFormSchema, TabFormActionType } from '/@/components/Form/src/types/form';
import { unref, computed, watch, createVNode } from 'vue';
import { useLocalization } from '/@/hooks/abp/useLocalization';
import { cloneDeep } from 'lodash-es';
import { listToTree } from '/@/utils/helper/treeHelper';

//自有模块
import { getList, create, update } from '/@/api/system/company';
import { Company, UpdateCompany, CreateCompany } from '/@/api/system/company/model';
import { AddressSelector } from '/@/components/Address'

interface UseCompanyFormContext {
  companyModel: Ref<Company>;
  formElRef: Ref<Nullable<TabFormActionType>>;
}

export function useCompanyFormContext({ companyModel, formElRef }: UseCompanyFormContext) {
  console.log("module is");
  console.log(companyModel);

  const { L } = useLocalization(['AppPlatform','System']);

  function getBasicFormSchemas(): TabFormSchema[] {
    return [
      {
        tab: L('DisplayName:Basic'),
        field: 'id',
        component: 'Input',
        label: 'id',
        colProps: { span: 24 },
        ifShow: false,
        required:true
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'name',
        component: 'Input',
        label: L('DisplayName:Name'),
        colProps: { span: 24 },
        required: true,
      },
      // {
      //   tab: L('DisplayName:Basic'),
      //   field: 'shortName',
      //   component: 'Input',
      //   label: L('DisplayName:ShortName'),
      //   colProps: { span: 24 },
      //   required: true,
      // },
      {
        tab: L('DisplayName:Basic'),
        field: 'shortName',
        component: 'AddressSelector',
        label: L('DisplayName:Address'),
        colProps: { span: 24 },
        //valueField:"valueX",//控件的哪个属性
        // componentProps: {
        //   valueX:{countryCode:'100000'}
        // },
        required: false,
      },
    ];
  }

  const getFormSchemas = computed((): TabFormSchema[] => {
    return [...getBasicFormSchemas()];
  });

  const formTitle = computed((): string => {
    const company = unref(companyModel);
    if(!company) return "";
    if (company.id) {
      return L('Menu:EditByName', [company.name] as Recordable);
    }
    return L('Menu:AddNew');
  });

  /* 使用此填充下拉列表
  async function fetchCompanyResource() {
    removeAllParentMenus();
    const formEl = unref(formElRef);
    const { items } = await getList({});
    const treeData = listToTree(items, { id: 'code', pid: 'parentCode' });
    const region = unref(regionModel);
    formEl?.updateSchema({
      field: 'parentCode',
      defaultValue: region.parentCode,
      componentProps: { treeData },
    });
  }
  */

  function handleFormSubmit() {
    const formEl = unref(formElRef);
    return formEl?.validate().then(() => {
      debugger;
      const model = unref(companyModel);
      const input = formEl?.getFieldsValue();
      return model.id
        ? update(model.id, cloneDeep(input) as UpdateCompany)
        : create(cloneDeep(input) as CreateCompany);
    });
  }

  watch(
    () => unref(companyModel),
    (newModel) => {
      const formEl = unref(formElRef);
      formEl?.resetFields();
      formEl?.setFieldsValue(newModel);
    },
    { immediate: true },
  );

  return {
    formTitle,
    getFormSchemas,
    handleFormSubmit,
    //fetchCompanyResource,
  };
}


