<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Zion.Product</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Zion.Product.Application\Zion.Product.Application.csproj" />
    <ProjectReference Include="..\Zion.Product.Domain.Tests\Zion.Product.Domain.Tests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>

</Project>
