// This class generated by CodeSmith on 2024年8月23日


import { number } from "vue-types";

export interface Ad{
  id: string;
  name: string;
}


export interface CreateOrUpdateAdBase {
  name: string;
}

export interface CreateAd extends CreateOrUpdateAdBase {
    
}

export interface UpdateAd extends CreateOrUpdateAdBase {

}

export interface GetAdPagedRequest extends PagedAndSortedResultRequestDto {
  name: string;
}

