// This class generated by CodeSmith on 2024年8月22日


<template>
  <BrandTable />
</template>

<script lang="ts">
  import { defineComponent } from 'vue';

  import BrandTable from './components/BrandTable.vue';
  export default defineComponent({
    name: 'Brands',
    components: {
      BrandTable,
    },
    setup() {},
  });
</script>
