// This class generated by CodeSmith on 2024年8月22日

//系统模块
import type { Ref } from 'vue';
import type { TabFormSchema, TabFormActionType } from '/@/components/Form/src/types/form';
import { unref, computed, watch, createVNode } from 'vue';
import { useLocalization } from '/@/hooks/abp/useLocalization';
import { cloneDeep } from 'lodash-es';
import { listToTree } from '/@/utils/helper/treeHelper';

//自有模块
import { getList, create, update } from '/@/api/product/unit';
import { Unit, UpdateUnit, CreateUnit } from '/@/api/product/unit/model';

interface UseUnitFormContext {
  unitModel: Ref<Unit>;
  formElRef: Ref<Nullable<TabFormActionType>>;
}

export function useUnitFormContext({ unitModel, formElRef }: UseUnitFormContext) {
  console.log("module is");
  console.log(unitModel);

  const { L } = useLocalization(['AppPlatform','System','Product']);

  function getBasicFormSchemas(): TabFormSchema[] {
    return [
      {
        tab: L('DisplayName:Basic'),
        field: 'id',
        component: 'Input',
        label: 'id',
        colProps: { span: 24 },
        ifShow: false,
        required:true
      },
      {
        tab: L('DisplayName:Basic'),
        field: 'name',
        component: 'Input',
        label: L('DisplayName:Name'),
        colProps: { span: 24 },
        required: true,
      },
    ];
  }

  const getFormSchemas = computed((): TabFormSchema[] => {
    return [...getBasicFormSchemas()];
  });

  const formTitle = computed((): string => {
    const unit = unref(unitModel);
    if(!unit) return "";
    if (unit.id) {
      return L('Menu:EditByName', [unit.name] as Recordable);
    }
    return L('Menu:AddNew');
  });

  /* 使用此填充下拉列表
  async function fetchUnitResource() {
    removeAllParentMenus();
    const formEl = unref(formElRef);
    const { items } = await getList({});
    const treeData = listToTree(items, { id: 'code', pid: 'parentCode' });
    const region = unref(regionModel);
    formEl?.updateSchema({
      field: 'parentCode',
      defaultValue: region.parentCode,
      componentProps: { treeData },
    });
  }
  */

  function handleFormSubmit() {
    const formEl = unref(formElRef);
    return formEl?.validate().then(() => {
      const model = unref(unitModel);
      const input = formEl?.getFieldsValue();
      return model.id
        ? update(model.id, cloneDeep(input) as UpdateUnit)
        : create(cloneDeep(input) as CreateUnit);
    });
  }

  watch(
    () => unref(unitModel),
    (newModel) => {
      const formEl = unref(formElRef);
      formEl?.resetFields();
      formEl?.setFieldsValue(newModel);
    },
    { immediate: true },
  );

  return {
    formTitle,
    getFormSchemas,
    handleFormSubmit,
    //fetchUnitResource,
  };
}


