<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\..\..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
        <RootNamespace>Zion.Sales</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Volo.Abp.VirtualFileSystem" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="..\..\Zion.Sales.abpmdl" />
      <Content Include="..\..\Zion.Sales.abpmdl">
        <Pack>true</Pack>
        <PackagePath>content\</PackagePath>
      </Content>
    </ItemGroup>

</Project>
